server:
  port: 8082
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-dev
    password: MyNewPass
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcomeMessage: Hello world-dev!!

management:
  endpoints:
    web:
      exposure:
#        include: "health, features"
        include: "*"
        exclude: "env"